version: '3.9'

services:
  postgres:
    image: postgres:18-alpine
    container_name: db-lab-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: labdb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - db-lab-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d labdb"]
      interval: 5s
      timeout: 3s
      retries: 5

networks:
  db-lab-net:
    driver: bridge

volumes:
  postgres-data:
    driver: local