
CREATE TEMP TABLE tmp_players (
    player_id INT,
    player_url TEXT,
    fifa_version SMALLINT,
    fifa_update SMALLINT,
    fifa_update_date DATE,
    short_name TEXT,
    long_name TEXT,
    player_positions TEXT,
    overall SMALLINT,
    potential SMALLINT,
    value_eur BIGINT,
    wage_eur INT,
    age SMALLINT,
    dob DATE,
    height_cm SMALLINT,
    weight_kg SMALLINT,
    league_id INT,
    league_name TEXT,
    league_level SMALLINT,
    club_team_id INT,
    club_name TEXT,
    club_position TEXT,
    club_jersey_number SMALLINT,
    club_loaned_from TEXT,
    club_joined_date DATE,
    club_contract_valid_until_year SMALLINT,
    nationality_id INT,
    nationality_name TEXT,
    nation_team_id INT,
    nation_position TEXT,
    nation_jersey_number SMALLINT,
    preferred_foot TEXT,
    weak_foot SMALLINT,
    skill_moves SMALLINT,
    international_reputation SMALLINT,
    work_rate TEXT,
    body_type TEXT,
    real_face BOOLEAN,
    release_clause_eur BIGINT,
    player_tags TEXT,
    player_traits TEXT,
    pace SMALLINT,
    shooting SMALLINT,
    passing SMALLINT,
    dribbling SMALLINT,
    defending SMALLINT,
    physic SMALLINT,
    attacking_crossing SMALLINT,
    attacking_finishing SMALLINT,
    attacking_heading_accuracy SMALLINT,
    attacking_short_passing SMALLINT,
    attacking_volleys SMALLINT,
    skill_dribbling SMALLINT,
    skill_curve SMALLINT,
    skill_fk_accuracy SMALLINT,
    skill_long_passing SMALLINT,
    skill_ball_control SMALLINT,
    movement_acceleration SMALLINT,
    movement_sprint_speed SMALLINT,
    movement_agility SMALLINT,
    movement_reactions SMALLINT,
    movement_balance SMALLINT,
    power_shot_power SMALLINT,
    power_jumping SMALLINT,
    power_stamina SMALLINT,
    power_strength SMALLINT,
    power_long_shots SMALLINT,
    mentality_aggression SMALLINT,
    mentality_interceptions SMALLINT,
    mentality_positioning SMALLINT,
    mentality_vision SMALLINT,
    mentality_penalties SMALLINT,
    mentality_composure SMALLINT,
    defending_marking_awareness SMALLINT,
    defending_standing_tackle SMALLINT,
    defending_sliding_tackle SMALLINT,
    goalkeeping_diving SMALLINT,
    goalkeeping_handling SMALLINT,
    goalkeeping_kicking SMALLINT,
    goalkeeping_positioning SMALLINT,
    goalkeeping_reflexes SMALLINT,
    goalkeeping_speed SMALLINT,
    ls TEXT,
    st TEXT,
    rs TEXT,
    lw TEXT,
    lf TEXT,
    cf TEXT,
    rf TEXT,
    rw TEXT,
    lam TEXT,
    cam TEXT,
    ram TEXT,
    lm TEXT,
    lcm TEXT,
    cm TEXT,
    rcm TEXT,
    rm TEXT,
    lwb TEXT,
    ldm TEXT,
    cdm TEXT,
    rdm TEXT,
    rwb TEXT,
    lb TEXT,
    lcb TEXT,
    cb TEXT,
    rcb TEXT,
    rb TEXT,
    gk TEXT,
    player_face_url TEXT
);

COPY tmp_players
FROM '/Players.csv'
DELIMITER ','
CSV HEADER
NULL '';

INSERT INTO players (
    player_id,
    player_url,
    fifa_version,
    fifa_update,
    fifa_update_date,
    short_name,
    long_name,
    player_positions,
    overall,
    potential,
    value_eur,
    wage_eur,
    age,
    dob,
    height_cm,
    weight_kg,
    league_id,
    league_name,
    league_level,
    club_team_id,
    club_name,
    club_position,
    club_jersey_number,
    club_loaned_from,
    club_joined_date,
    club_contract_valid_until_year,
    nationality_id,
    nationality_name,
    nation_team_id,
    nation_position,
    nation_jersey_number,
    preferred_foot,
    weak_foot,
    skill_moves,
    international_reputation,
    work_rate,
    body_type,
    real_face,
    release_clause_eur,
    player_tags,
    player_traits,
    pace,
    shooting,
    passing,
    dribbling,
    defending,
    physic,
    attacking_crossing,
    attacking_finishing,
    attacking_heading_accuracy,
    attacking_short_passing,
    attacking_volleys,
    skill_dribbling,
    skill_curve,
    skill_fk_accuracy,
    skill_long_passing,
    skill_ball_control,
    movement_acceleration,
    movement_sprint_speed,
    movement_agility,
    movement_reactions,
    movement_balance,
    power_shot_power,
    power_jumping,
    power_stamina,
    power_strength,
    power_long_shots,
    mentality_aggression,
    mentality_interceptions,
    mentality_positioning,
    mentality_vision,
    mentality_penalties,
    mentality_composure,
    defending_marking_awareness,
    defending_standing_tackle,
    defending_sliding_tackle,
    goalkeeping_diving,
    goalkeeping_handling,
    goalkeeping_kicking,
    goalkeeping_positioning,
    goalkeeping_reflexes,
    goalkeeping_speed,
    ls,
    st,
    rs,
    lw,
    lf,
    cf,
    rf,
    rw,
    lam,
    cam,
    ram,
    lm,
    lcm,
    cm,
    rcm,
    rm,
    lwb,
    ldm,
    cdm,
    rdm,
    rwb,
    lb,
    lcb,
    cb,
    rcb,
    rb,
    gk,
    player_face_url
)

SELECT
    player_id,
    player_url,
    fifa_version,
    fifa_update,
    fifa_update_date,
    short_name,
    long_name,
    player_positions,
    overall,
    potential,
    value_eur,
    wage_eur,
    age,
    dob,
    height_cm,
    weight_kg,
    league_id,
    league_name,
    league_level,
    club_team_id,
    club_name,
    club_position,
    club_jersey_number,
    club_loaned_from,
    club_joined_date,
    club_contract_valid_until_year,
    nationality_id,
    nationality_name,
    nation_team_id,
    nation_position,
    nation_jersey_number,
    preferred_foot,
    weak_foot,
    skill_moves,
    international_reputation,
    work_rate,
    body_type,
    real_face,
    release_clause_eur,
    player_tags,
    player_traits,
    pace,
    shooting,
    passing,
    dribbling,
    defending,
    physic,
    attacking_crossing,
    attacking_finishing,
    attacking_heading_accuracy,
    attacking_short_passing,
    attacking_volleys,
    skill_dribbling,
    skill_curve,
    skill_fk_accuracy,
    skill_long_passing,
    skill_ball_control,
    movement_acceleration,
    movement_sprint_speed,
    movement_agility,
    movement_reactions,
    movement_balance,
    power_shot_power,
    power_jumping,
    power_stamina,
    power_strength,
    power_long_shots,
    mentality_aggression,
    mentality_interceptions,
    mentality_positioning,
    mentality_vision,
    mentality_penalties,
    mentality_composure,
    defending_marking_awareness,
    defending_standing_tackle,
    defending_sliding_tackle,
    goalkeeping_diving,
    goalkeeping_handling,
    goalkeeping_kicking,
    goalkeeping_positioning,
    goalkeeping_reflexes,
    goalkeeping_speed,
    ls,
    st,
    rs,
    lw,
    lf,
    cf,
    rf,
    rw,
    lam,
    cam,
    ram,
    lm,
    lcm,
    cm,
    rcm,
    rm,
    lwb,
    ldm,
    cdm,
    rdm,
    rwb,
    lb,
    lcb,
    cb,
    rcb,
    rb,
    gk,
    player_face_url

FROM tmp_players;
