// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package repository

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.addPlayerToSquadStmt, err = db.PrepareContext(ctx, addPlayerToSquad); err != nil {
		return nil, fmt.Errorf("error preparing query AddPlayerToSquad: %w", err)
	}
	if q.countPlayersFromNationInSquadStmt, err = db.PrepareContext(ctx, countPlayersFromNationInSquad); err != nil {
		return nil, fmt.Errorf("error preparing query CountPlayersFromNationInSquad: %w", err)
	}
	if q.countPlayersInSquadStmt, err = db.PrepareContext(ctx, countPlayersInSquad); err != nil {
		return nil, fmt.Errorf("error preparing query CountPlayersInSquad: %w", err)
	}
	if q.createMatchStmt, err = db.PrepareContext(ctx, createMatch); err != nil {
		return nil, fmt.Errorf("error preparing query CreateMatch: %w", err)
	}
	if q.createMatchUserPlayerPointsStmt, err = db.PrepareContext(ctx, createMatchUserPlayerPoints); err != nil {
		return nil, fmt.Errorf("error preparing query CreateMatchUserPlayerPoints: %w", err)
	}
	if q.createMatchUserPointsStmt, err = db.PrepareContext(ctx, createMatchUserPoints); err != nil {
		return nil, fmt.Errorf("error preparing query CreateMatchUserPoints: %w", err)
	}
	if q.createSquadStmt, err = db.PrepareContext(ctx, createSquad); err != nil {
		return nil, fmt.Errorf("error preparing query CreateSquad: %w", err)
	}
	if q.createUserStmt, err = db.PrepareContext(ctx, createUser); err != nil {
		return nil, fmt.Errorf("error preparing query CreateUser: %w", err)
	}
	if q.getLeaderboardStmt, err = db.PrepareContext(ctx, getLeaderboard); err != nil {
		return nil, fmt.Errorf("error preparing query GetLeaderboard: %w", err)
	}
	if q.getLeaderboardPageStmt, err = db.PrepareContext(ctx, getLeaderboardPage); err != nil {
		return nil, fmt.Errorf("error preparing query GetLeaderboardPage: %w", err)
	}
	if q.getMatchByIDStmt, err = db.PrepareContext(ctx, getMatchByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetMatchByID: %w", err)
	}
	if q.getPlayerStmt, err = db.PrepareContext(ctx, getPlayer); err != nil {
		return nil, fmt.Errorf("error preparing query GetPlayer: %w", err)
	}
	if q.getSquadByUserIDStmt, err = db.PrepareContext(ctx, getSquadByUserID); err != nil {
		return nil, fmt.Errorf("error preparing query GetSquadByUserID: %w", err)
	}
	if q.getSquadPlayersStmt, err = db.PrepareContext(ctx, getSquadPlayers); err != nil {
		return nil, fmt.Errorf("error preparing query GetSquadPlayers: %w", err)
	}
	if q.getUserByEmailStmt, err = db.PrepareContext(ctx, getUserByEmail); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserByEmail: %w", err)
	}
	if q.getUserByIDStmt, err = db.PrepareContext(ctx, getUserByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserByID: %w", err)
	}
	if q.getUserByUsernameStmt, err = db.PrepareContext(ctx, getUserByUsername); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserByUsername: %w", err)
	}
	if q.getUserLeaderboardPositionStmt, err = db.PrepareContext(ctx, getUserLeaderboardPosition); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserLeaderboardPosition: %w", err)
	}
	if q.getUserScoringHistoryStmt, err = db.PrepareContext(ctx, getUserScoringHistory); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserScoringHistory: %w", err)
	}
	if q.getUserScoringHistoryByMatchStmt, err = db.PrepareContext(ctx, getUserScoringHistoryByMatch); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserScoringHistoryByMatch: %w", err)
	}
	if q.getUserTotalPointsStmt, err = db.PrepareContext(ctx, getUserTotalPoints); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserTotalPoints: %w", err)
	}
	if q.incrementSquadTotalPointsStmt, err = db.PrepareContext(ctx, incrementSquadTotalPoints); err != nil {
		return nil, fmt.Errorf("error preparing query IncrementSquadTotalPoints: %w", err)
	}
	if q.listMatchesStmt, err = db.PrepareContext(ctx, listMatches); err != nil {
		return nil, fmt.Errorf("error preparing query ListMatches: %w", err)
	}
	if q.listPlayersStmt, err = db.PrepareContext(ctx, listPlayers); err != nil {
		return nil, fmt.Errorf("error preparing query ListPlayers: %w", err)
	}
	if q.listSquadsForScoringStmt, err = db.PrepareContext(ctx, listSquadsForScoring); err != nil {
		return nil, fmt.Errorf("error preparing query ListSquadsForScoring: %w", err)
	}
	if q.removePlayerFromSquadStmt, err = db.PrepareContext(ctx, removePlayerFromSquad); err != nil {
		return nil, fmt.Errorf("error preparing query RemovePlayerFromSquad: %w", err)
	}
	if q.searchPlayersStmt, err = db.PrepareContext(ctx, searchPlayers); err != nil {
		return nil, fmt.Errorf("error preparing query SearchPlayers: %w", err)
	}
	if q.updatePointsForNationStmt, err = db.PrepareContext(ctx, updatePointsForNation); err != nil {
		return nil, fmt.Errorf("error preparing query UpdatePointsForNation: %w", err)
	}
	if q.updateSquadBudgetStmt, err = db.PrepareContext(ctx, updateSquadBudget); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateSquadBudget: %w", err)
	}
	if q.updateSquadFormationStmt, err = db.PrepareContext(ctx, updateSquadFormation); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateSquadFormation: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.addPlayerToSquadStmt != nil {
		if cerr := q.addPlayerToSquadStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing addPlayerToSquadStmt: %w", cerr)
		}
	}
	if q.countPlayersFromNationInSquadStmt != nil {
		if cerr := q.countPlayersFromNationInSquadStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countPlayersFromNationInSquadStmt: %w", cerr)
		}
	}
	if q.countPlayersInSquadStmt != nil {
		if cerr := q.countPlayersInSquadStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countPlayersInSquadStmt: %w", cerr)
		}
	}
	if q.createMatchStmt != nil {
		if cerr := q.createMatchStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createMatchStmt: %w", cerr)
		}
	}
	if q.createMatchUserPlayerPointsStmt != nil {
		if cerr := q.createMatchUserPlayerPointsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createMatchUserPlayerPointsStmt: %w", cerr)
		}
	}
	if q.createMatchUserPointsStmt != nil {
		if cerr := q.createMatchUserPointsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createMatchUserPointsStmt: %w", cerr)
		}
	}
	if q.createSquadStmt != nil {
		if cerr := q.createSquadStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createSquadStmt: %w", cerr)
		}
	}
	if q.createUserStmt != nil {
		if cerr := q.createUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createUserStmt: %w", cerr)
		}
	}
	if q.getLeaderboardStmt != nil {
		if cerr := q.getLeaderboardStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getLeaderboardStmt: %w", cerr)
		}
	}
	if q.getLeaderboardPageStmt != nil {
		if cerr := q.getLeaderboardPageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getLeaderboardPageStmt: %w", cerr)
		}
	}
	if q.getMatchByIDStmt != nil {
		if cerr := q.getMatchByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getMatchByIDStmt: %w", cerr)
		}
	}
	if q.getPlayerStmt != nil {
		if cerr := q.getPlayerStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getPlayerStmt: %w", cerr)
		}
	}
	if q.getSquadByUserIDStmt != nil {
		if cerr := q.getSquadByUserIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getSquadByUserIDStmt: %w", cerr)
		}
	}
	if q.getSquadPlayersStmt != nil {
		if cerr := q.getSquadPlayersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getSquadPlayersStmt: %w", cerr)
		}
	}
	if q.getUserByEmailStmt != nil {
		if cerr := q.getUserByEmailStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserByEmailStmt: %w", cerr)
		}
	}
	if q.getUserByIDStmt != nil {
		if cerr := q.getUserByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserByIDStmt: %w", cerr)
		}
	}
	if q.getUserByUsernameStmt != nil {
		if cerr := q.getUserByUsernameStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserByUsernameStmt: %w", cerr)
		}
	}
	if q.getUserLeaderboardPositionStmt != nil {
		if cerr := q.getUserLeaderboardPositionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserLeaderboardPositionStmt: %w", cerr)
		}
	}
	if q.getUserScoringHistoryStmt != nil {
		if cerr := q.getUserScoringHistoryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserScoringHistoryStmt: %w", cerr)
		}
	}
	if q.getUserScoringHistoryByMatchStmt != nil {
		if cerr := q.getUserScoringHistoryByMatchStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserScoringHistoryByMatchStmt: %w", cerr)
		}
	}
	if q.getUserTotalPointsStmt != nil {
		if cerr := q.getUserTotalPointsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserTotalPointsStmt: %w", cerr)
		}
	}
	if q.incrementSquadTotalPointsStmt != nil {
		if cerr := q.incrementSquadTotalPointsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing incrementSquadTotalPointsStmt: %w", cerr)
		}
	}
	if q.listMatchesStmt != nil {
		if cerr := q.listMatchesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listMatchesStmt: %w", cerr)
		}
	}
	if q.listPlayersStmt != nil {
		if cerr := q.listPlayersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listPlayersStmt: %w", cerr)
		}
	}
	if q.listSquadsForScoringStmt != nil {
		if cerr := q.listSquadsForScoringStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listSquadsForScoringStmt: %w", cerr)
		}
	}
	if q.removePlayerFromSquadStmt != nil {
		if cerr := q.removePlayerFromSquadStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing removePlayerFromSquadStmt: %w", cerr)
		}
	}
	if q.searchPlayersStmt != nil {
		if cerr := q.searchPlayersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing searchPlayersStmt: %w", cerr)
		}
	}
	if q.updatePointsForNationStmt != nil {
		if cerr := q.updatePointsForNationStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updatePointsForNationStmt: %w", cerr)
		}
	}
	if q.updateSquadBudgetStmt != nil {
		if cerr := q.updateSquadBudgetStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateSquadBudgetStmt: %w", cerr)
		}
	}
	if q.updateSquadFormationStmt != nil {
		if cerr := q.updateSquadFormationStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateSquadFormationStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                                DBTX
	tx                                *sql.Tx
	addPlayerToSquadStmt              *sql.Stmt
	countPlayersFromNationInSquadStmt *sql.Stmt
	countPlayersInSquadStmt           *sql.Stmt
	createMatchStmt                   *sql.Stmt
	createMatchUserPlayerPointsStmt   *sql.Stmt
	createMatchUserPointsStmt         *sql.Stmt
	createSquadStmt                   *sql.Stmt
	createUserStmt                    *sql.Stmt
	getLeaderboardStmt                *sql.Stmt
	getLeaderboardPageStmt            *sql.Stmt
	getMatchByIDStmt                  *sql.Stmt
	getPlayerStmt                     *sql.Stmt
	getSquadByUserIDStmt              *sql.Stmt
	getSquadPlayersStmt               *sql.Stmt
	getUserByEmailStmt                *sql.Stmt
	getUserByIDStmt                   *sql.Stmt
	getUserByUsernameStmt             *sql.Stmt
	getUserLeaderboardPositionStmt    *sql.Stmt
	getUserScoringHistoryStmt         *sql.Stmt
	getUserScoringHistoryByMatchStmt  *sql.Stmt
	getUserTotalPointsStmt            *sql.Stmt
	incrementSquadTotalPointsStmt     *sql.Stmt
	listMatchesStmt                   *sql.Stmt
	listPlayersStmt                   *sql.Stmt
	listSquadsForScoringStmt          *sql.Stmt
	removePlayerFromSquadStmt         *sql.Stmt
	searchPlayersStmt                 *sql.Stmt
	updatePointsForNationStmt         *sql.Stmt
	updateSquadBudgetStmt             *sql.Stmt
	updateSquadFormationStmt          *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                                tx,
		tx:                                tx,
		addPlayerToSquadStmt:              q.addPlayerToSquadStmt,
		countPlayersFromNationInSquadStmt: q.countPlayersFromNationInSquadStmt,
		countPlayersInSquadStmt:           q.countPlayersInSquadStmt,
		createMatchStmt:                   q.createMatchStmt,
		createMatchUserPlayerPointsStmt:   q.createMatchUserPlayerPointsStmt,
		createMatchUserPointsStmt:         q.createMatchUserPointsStmt,
		createSquadStmt:                   q.createSquadStmt,
		createUserStmt:                    q.createUserStmt,
		getLeaderboardStmt:                q.getLeaderboardStmt,
		getLeaderboardPageStmt:            q.getLeaderboardPageStmt,
		getMatchByIDStmt:                  q.getMatchByIDStmt,
		getPlayerStmt:                     q.getPlayerStmt,
		getSquadByUserIDStmt:              q.getSquadByUserIDStmt,
		getSquadPlayersStmt:               q.getSquadPlayersStmt,
		getUserByEmailStmt:                q.getUserByEmailStmt,
		getUserByIDStmt:                   q.getUserByIDStmt,
		getUserByUsernameStmt:             q.getUserByUsernameStmt,
		getUserLeaderboardPositionStmt:    q.getUserLeaderboardPositionStmt,
		getUserScoringHistoryStmt:         q.getUserScoringHistoryStmt,
		getUserScoringHistoryByMatchStmt:  q.getUserScoringHistoryByMatchStmt,
		getUserTotalPointsStmt:            q.getUserTotalPointsStmt,
		incrementSquadTotalPointsStmt:     q.incrementSquadTotalPointsStmt,
		listMatchesStmt:                   q.listMatchesStmt,
		listPlayersStmt:                   q.listPlayersStmt,
		listSquadsForScoringStmt:          q.listSquadsForScoringStmt,
		removePlayerFromSquadStmt:         q.removePlayerFromSquadStmt,
		searchPlayersStmt:                 q.searchPlayersStmt,
		updatePointsForNationStmt:         q.updatePointsForNationStmt,
		updateSquadBudgetStmt:             q.updateSquadBudgetStmt,
		updateSquadFormationStmt:          q.updateSquadFormationStmt,
	}
}
