// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package repository

import (
	"database/sql"
)

type Player struct {
	PlayerID                   int32          `json:"player_id"`
	PlayerUrl                  sql.NullString `json:"player_url"`
	FifaVersion                sql.NullInt16  `json:"fifa_version"`
	FifaUpdate                 sql.NullInt16  `json:"fifa_update"`
	FifaUpdateDate             sql.NullTime   `json:"fifa_update_date"`
	ShortName                  sql.NullString `json:"short_name"`
	LongName                   sql.NullString `json:"long_name"`
	PlayerPositions            sql.NullString `json:"player_positions"`
	Overall                    sql.NullInt16  `json:"overall"`
	Potential                  sql.NullInt16  `json:"potential"`
	ValueEur                   sql.NullInt64  `json:"value_eur"`
	WageEur                    sql.NullInt32  `json:"wage_eur"`
	Age                        sql.NullInt16  `json:"age"`
	Dob                        sql.NullTime   `json:"dob"`
	HeightCm                   sql.NullInt16  `json:"height_cm"`
	WeightKg                   sql.NullInt16  `json:"weight_kg"`
	LeagueID                   sql.NullInt32  `json:"league_id"`
	LeagueName                 sql.NullString `json:"league_name"`
	LeagueLevel                sql.NullInt16  `json:"league_level"`
	ClubTeamID                 sql.NullInt32  `json:"club_team_id"`
	ClubName                   sql.NullString `json:"club_name"`
	ClubPosition               sql.NullString `json:"club_position"`
	ClubJerseyNumber           sql.NullInt16  `json:"club_jersey_number"`
	ClubLoanedFrom             sql.NullString `json:"club_loaned_from"`
	ClubJoinedDate             sql.NullTime   `json:"club_joined_date"`
	ClubContractValidUntilYear sql.NullInt16  `json:"club_contract_valid_until_year"`
	NationalityID              sql.NullInt32  `json:"nationality_id"`
	NationalityName            sql.NullString `json:"nationality_name"`
	NationTeamID               sql.NullInt32  `json:"nation_team_id"`
	NationPosition             sql.NullString `json:"nation_position"`
	NationJerseyNumber         sql.NullInt16  `json:"nation_jersey_number"`
	PreferredFoot              sql.NullString `json:"preferred_foot"`
	WeakFoot                   sql.NullInt16  `json:"weak_foot"`
	SkillMoves                 sql.NullInt16  `json:"skill_moves"`
	InternationalReputation    sql.NullInt16  `json:"international_reputation"`
	WorkRate                   sql.NullString `json:"work_rate"`
	BodyType                   sql.NullString `json:"body_type"`
	RealFace                   sql.NullBool   `json:"real_face"`
	ReleaseClauseEur           sql.NullInt64  `json:"release_clause_eur"`
	PlayerTags                 sql.NullString `json:"player_tags"`
	PlayerTraits               sql.NullString `json:"player_traits"`
	Pace                       sql.NullInt16  `json:"pace"`
	Shooting                   sql.NullInt16  `json:"shooting"`
	Passing                    sql.NullInt16  `json:"passing"`
	Dribbling                  sql.NullInt16  `json:"dribbling"`
	Defending                  sql.NullInt16  `json:"defending"`
	Physic                     sql.NullInt16  `json:"physic"`
	AttackingCrossing          sql.NullInt16  `json:"attacking_crossing"`
	AttackingFinishing         sql.NullInt16  `json:"attacking_finishing"`
	AttackingHeadingAccuracy   sql.NullInt16  `json:"attacking_heading_accuracy"`
	AttackingShortPassing      sql.NullInt16  `json:"attacking_short_passing"`
	AttackingVolleys           sql.NullInt16  `json:"attacking_volleys"`
	SkillDribbling             sql.NullInt16  `json:"skill_dribbling"`
	SkillCurve                 sql.NullInt16  `json:"skill_curve"`
	SkillFkAccuracy            sql.NullInt16  `json:"skill_fk_accuracy"`
	SkillLongPassing           sql.NullInt16  `json:"skill_long_passing"`
	SkillBallControl           sql.NullInt16  `json:"skill_ball_control"`
	MovementAcceleration       sql.NullInt16  `json:"movement_acceleration"`
	MovementSprintSpeed        sql.NullInt16  `json:"movement_sprint_speed"`
	MovementAgility            sql.NullInt16  `json:"movement_agility"`
	MovementReactions          sql.NullInt16  `json:"movement_reactions"`
	MovementBalance            sql.NullInt16  `json:"movement_balance"`
	PowerShotPower             sql.NullInt16  `json:"power_shot_power"`
	PowerJumping               sql.NullInt16  `json:"power_jumping"`
	PowerStamina               sql.NullInt16  `json:"power_stamina"`
	PowerStrength              sql.NullInt16  `json:"power_strength"`
	PowerLongShots             sql.NullInt16  `json:"power_long_shots"`
	MentalityAggression        sql.NullInt16  `json:"mentality_aggression"`
	MentalityInterceptions     sql.NullInt16  `json:"mentality_interceptions"`
	MentalityPositioning       sql.NullInt16  `json:"mentality_positioning"`
	MentalityVision            sql.NullInt16  `json:"mentality_vision"`
	MentalityPenalties         sql.NullInt16  `json:"mentality_penalties"`
	MentalityComposure         sql.NullInt16  `json:"mentality_composure"`
	DefendingMarkingAwareness  sql.NullInt16  `json:"defending_marking_awareness"`
	DefendingStandingTackle    sql.NullInt16  `json:"defending_standing_tackle"`
	DefendingSlidingTackle     sql.NullInt16  `json:"defending_sliding_tackle"`
	GoalkeepingDiving          sql.NullInt16  `json:"goalkeeping_diving"`
	GoalkeepingHandling        sql.NullInt16  `json:"goalkeeping_handling"`
	GoalkeepingKicking         sql.NullInt16  `json:"goalkeeping_kicking"`
	GoalkeepingPositioning     sql.NullInt16  `json:"goalkeeping_positioning"`
	GoalkeepingReflexes        sql.NullInt16  `json:"goalkeeping_reflexes"`
	GoalkeepingSpeed           sql.NullInt16  `json:"goalkeeping_speed"`
	Ls                         sql.NullString `json:"ls"`
	St                         sql.NullString `json:"st"`
	Rs                         sql.NullString `json:"rs"`
	Lw                         sql.NullString `json:"lw"`
	Lf                         sql.NullString `json:"lf"`
	Cf                         sql.NullString `json:"cf"`
	Rf                         sql.NullString `json:"rf"`
	Rw                         sql.NullString `json:"rw"`
	Lam                        sql.NullString `json:"lam"`
	Cam                        sql.NullString `json:"cam"`
	Ram                        sql.NullString `json:"ram"`
	Lm                         sql.NullString `json:"lm"`
	Lcm                        sql.NullString `json:"lcm"`
	Cm                         sql.NullString `json:"cm"`
	Rcm                        sql.NullString `json:"rcm"`
	Rm                         sql.NullString `json:"rm"`
	Lwb                        sql.NullString `json:"lwb"`
	Ldm                        sql.NullString `json:"ldm"`
	Cdm                        sql.NullString `json:"cdm"`
	Rdm                        sql.NullString `json:"rdm"`
	Rwb                        sql.NullString `json:"rwb"`
	Lb                         sql.NullString `json:"lb"`
	Lcb                        sql.NullString `json:"lcb"`
	Cb                         sql.NullString `json:"cb"`
	Rcb                        sql.NullString `json:"rcb"`
	Rb                         sql.NullString `json:"rb"`
	Gk                         sql.NullString `json:"gk"`
	PlayerFaceUrl              sql.NullString `json:"player_face_url"`
}

type Squad struct {
	SquadID     int32          `json:"squad_id"`
	UserID      int32          `json:"user_id"`
	SquadName   string         `json:"squad_name"`
	Formation   sql.NullString `json:"formation"`
	BudgetUsed  sql.NullInt64  `json:"budget_used"`
	TotalPoints sql.NullInt32  `json:"total_points"`
}

type SquadPlayer struct {
	SquadID      int32          `json:"squad_id"`
	PlayerID     int32          `json:"player_id"`
	PositionSlot sql.NullString `json:"position_slot"`
}

type User struct {
	UserID       int32  `json:"user_id"`
	Username     string `json:"username"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
}
