// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package repository

import (
	"context"
	"database/sql"
)

const addPlayerToSquad = `-- name: AddPlayerToSquad :exec
INSERT INTO squad_player (squad_id, player_id, position_slot)
VALUES ($1, $2, $3)
`

type AddPlayerToSquadParams struct {
	SquadID      int32          `json:"squad_id"`
	PlayerID     int32          `json:"player_id"`
	PositionSlot sql.NullString `json:"position_slot"`
}

func (q *Queries) AddPlayerToSquad(ctx context.Context, arg AddPlayerToSquadParams) error {
	_, err := q.exec(ctx, q.addPlayerToSquadStmt, addPlayerToSquad, arg.SquadID, arg.PlayerID, arg.PositionSlot)
	return err
}

const countPlayersFromNationInSquad = `-- name: CountPlayersFromNationInSquad :one
SELECT COUNT(*)
FROM players p
JOIN squad_player sp ON p.player_id = sp.player_id
WHERE sp.squad_id = $1 AND p.nationality_id = $2
`

type CountPlayersFromNationInSquadParams struct {
	SquadID       int32         `json:"squad_id"`
	NationalityID sql.NullInt32 `json:"nationality_id"`
}

func (q *Queries) CountPlayersFromNationInSquad(ctx context.Context, arg CountPlayersFromNationInSquadParams) (int64, error) {
	row := q.queryRow(ctx, q.countPlayersFromNationInSquadStmt, countPlayersFromNationInSquad, arg.SquadID, arg.NationalityID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPlayersInSquad = `-- name: CountPlayersInSquad :one
SELECT COUNT(*) FROM squad_player
WHERE squad_id = $1
`

func (q *Queries) CountPlayersInSquad(ctx context.Context, squadID int32) (int64, error) {
	row := q.queryRow(ctx, q.countPlayersInSquadStmt, countPlayersInSquad, squadID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSquad = `-- name: CreateSquad :one
INSERT INTO squad (user_id, squad_name, formation, budget_used)
VALUES ($1, $2, $3, $4)
RETURNING squad_id, user_id, squad_name, formation, budget_used, total_points
`

type CreateSquadParams struct {
	UserID     int32          `json:"user_id"`
	SquadName  string         `json:"squad_name"`
	Formation  sql.NullString `json:"formation"`
	BudgetUsed sql.NullInt64  `json:"budget_used"`
}

func (q *Queries) CreateSquad(ctx context.Context, arg CreateSquadParams) (Squad, error) {
	row := q.queryRow(ctx, q.createSquadStmt, createSquad,
		arg.UserID,
		arg.SquadName,
		arg.Formation,
		arg.BudgetUsed,
	)
	var i Squad
	err := row.Scan(
		&i.SquadID,
		&i.UserID,
		&i.SquadName,
		&i.Formation,
		&i.BudgetUsed,
		&i.TotalPoints,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, email, password_hash)
VALUES ($1, $2, $3)
RETURNING user_id, username, email, password_hash
`

type CreateUserParams struct {
	Username     string `json:"username"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.queryRow(ctx, q.createUserStmt, createUser, arg.Username, arg.Email, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
	)
	return i, err
}

const getLeaderboard = `-- name: GetLeaderboard :many
SELECT u.username, s.squad_name, s.total_points
FROM squad s
JOIN users u ON s.user_id = u.user_id
ORDER BY s.total_points DESC
LIMIT $1 OFFSET $2
`

type GetLeaderboardParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type GetLeaderboardRow struct {
	Username    string        `json:"username"`
	SquadName   string        `json:"squad_name"`
	TotalPoints sql.NullInt32 `json:"total_points"`
}

func (q *Queries) GetLeaderboard(ctx context.Context, arg GetLeaderboardParams) ([]GetLeaderboardRow, error) {
	rows, err := q.query(ctx, q.getLeaderboardStmt, getLeaderboard, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLeaderboardRow
	for rows.Next() {
		var i GetLeaderboardRow
		if err := rows.Scan(&i.Username, &i.SquadName, &i.TotalPoints); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlayer = `-- name: GetPlayer :one
SELECT player_id, player_url, fifa_version, fifa_update, fifa_update_date, short_name, long_name, player_positions, overall, potential, value_eur, wage_eur, age, dob, height_cm, weight_kg, league_id, league_name, league_level, club_team_id, club_name, club_position, club_jersey_number, club_loaned_from, club_joined_date, club_contract_valid_until_year, nationality_id, nationality_name, nation_team_id, nation_position, nation_jersey_number, preferred_foot, weak_foot, skill_moves, international_reputation, work_rate, body_type, real_face, release_clause_eur, player_tags, player_traits, pace, shooting, passing, dribbling, defending, physic, attacking_crossing, attacking_finishing, attacking_heading_accuracy, attacking_short_passing, attacking_volleys, skill_dribbling, skill_curve, skill_fk_accuracy, skill_long_passing, skill_ball_control, movement_acceleration, movement_sprint_speed, movement_agility, movement_reactions, movement_balance, power_shot_power, power_jumping, power_stamina, power_strength, power_long_shots, mentality_aggression, mentality_interceptions, mentality_positioning, mentality_vision, mentality_penalties, mentality_composure, defending_marking_awareness, defending_standing_tackle, defending_sliding_tackle, goalkeeping_diving, goalkeeping_handling, goalkeeping_kicking, goalkeeping_positioning, goalkeeping_reflexes, goalkeeping_speed, ls, st, rs, lw, lf, cf, rf, rw, lam, cam, ram, lm, lcm, cm, rcm, rm, lwb, ldm, cdm, rdm, rwb, lb, lcb, cb, rcb, rb, gk, player_face_url FROM players
WHERE player_id = $1 LIMIT 1
`

func (q *Queries) GetPlayer(ctx context.Context, playerID int32) (Player, error) {
	row := q.queryRow(ctx, q.getPlayerStmt, getPlayer, playerID)
	var i Player
	err := row.Scan(
		&i.PlayerID,
		&i.PlayerUrl,
		&i.FifaVersion,
		&i.FifaUpdate,
		&i.FifaUpdateDate,
		&i.ShortName,
		&i.LongName,
		&i.PlayerPositions,
		&i.Overall,
		&i.Potential,
		&i.ValueEur,
		&i.WageEur,
		&i.Age,
		&i.Dob,
		&i.HeightCm,
		&i.WeightKg,
		&i.LeagueID,
		&i.LeagueName,
		&i.LeagueLevel,
		&i.ClubTeamID,
		&i.ClubName,
		&i.ClubPosition,
		&i.ClubJerseyNumber,
		&i.ClubLoanedFrom,
		&i.ClubJoinedDate,
		&i.ClubContractValidUntilYear,
		&i.NationalityID,
		&i.NationalityName,
		&i.NationTeamID,
		&i.NationPosition,
		&i.NationJerseyNumber,
		&i.PreferredFoot,
		&i.WeakFoot,
		&i.SkillMoves,
		&i.InternationalReputation,
		&i.WorkRate,
		&i.BodyType,
		&i.RealFace,
		&i.ReleaseClauseEur,
		&i.PlayerTags,
		&i.PlayerTraits,
		&i.Pace,
		&i.Shooting,
		&i.Passing,
		&i.Dribbling,
		&i.Defending,
		&i.Physic,
		&i.AttackingCrossing,
		&i.AttackingFinishing,
		&i.AttackingHeadingAccuracy,
		&i.AttackingShortPassing,
		&i.AttackingVolleys,
		&i.SkillDribbling,
		&i.SkillCurve,
		&i.SkillFkAccuracy,
		&i.SkillLongPassing,
		&i.SkillBallControl,
		&i.MovementAcceleration,
		&i.MovementSprintSpeed,
		&i.MovementAgility,
		&i.MovementReactions,
		&i.MovementBalance,
		&i.PowerShotPower,
		&i.PowerJumping,
		&i.PowerStamina,
		&i.PowerStrength,
		&i.PowerLongShots,
		&i.MentalityAggression,
		&i.MentalityInterceptions,
		&i.MentalityPositioning,
		&i.MentalityVision,
		&i.MentalityPenalties,
		&i.MentalityComposure,
		&i.DefendingMarkingAwareness,
		&i.DefendingStandingTackle,
		&i.DefendingSlidingTackle,
		&i.GoalkeepingDiving,
		&i.GoalkeepingHandling,
		&i.GoalkeepingKicking,
		&i.GoalkeepingPositioning,
		&i.GoalkeepingReflexes,
		&i.GoalkeepingSpeed,
		&i.Ls,
		&i.St,
		&i.Rs,
		&i.Lw,
		&i.Lf,
		&i.Cf,
		&i.Rf,
		&i.Rw,
		&i.Lam,
		&i.Cam,
		&i.Ram,
		&i.Lm,
		&i.Lcm,
		&i.Cm,
		&i.Rcm,
		&i.Rm,
		&i.Lwb,
		&i.Ldm,
		&i.Cdm,
		&i.Rdm,
		&i.Rwb,
		&i.Lb,
		&i.Lcb,
		&i.Cb,
		&i.Rcb,
		&i.Rb,
		&i.Gk,
		&i.PlayerFaceUrl,
	)
	return i, err
}

const getSquadByUserID = `-- name: GetSquadByUserID :one
SELECT squad_id, user_id, squad_name, formation, budget_used, total_points FROM squad
WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetSquadByUserID(ctx context.Context, userID int32) (Squad, error) {
	row := q.queryRow(ctx, q.getSquadByUserIDStmt, getSquadByUserID, userID)
	var i Squad
	err := row.Scan(
		&i.SquadID,
		&i.UserID,
		&i.SquadName,
		&i.Formation,
		&i.BudgetUsed,
		&i.TotalPoints,
	)
	return i, err
}

const getSquadPlayers = `-- name: GetSquadPlayers :many
SELECT p.player_id, p.player_url, p.fifa_version, p.fifa_update, p.fifa_update_date, p.short_name, p.long_name, p.player_positions, p.overall, p.potential, p.value_eur, p.wage_eur, p.age, p.dob, p.height_cm, p.weight_kg, p.league_id, p.league_name, p.league_level, p.club_team_id, p.club_name, p.club_position, p.club_jersey_number, p.club_loaned_from, p.club_joined_date, p.club_contract_valid_until_year, p.nationality_id, p.nationality_name, p.nation_team_id, p.nation_position, p.nation_jersey_number, p.preferred_foot, p.weak_foot, p.skill_moves, p.international_reputation, p.work_rate, p.body_type, p.real_face, p.release_clause_eur, p.player_tags, p.player_traits, p.pace, p.shooting, p.passing, p.dribbling, p.defending, p.physic, p.attacking_crossing, p.attacking_finishing, p.attacking_heading_accuracy, p.attacking_short_passing, p.attacking_volleys, p.skill_dribbling, p.skill_curve, p.skill_fk_accuracy, p.skill_long_passing, p.skill_ball_control, p.movement_acceleration, p.movement_sprint_speed, p.movement_agility, p.movement_reactions, p.movement_balance, p.power_shot_power, p.power_jumping, p.power_stamina, p.power_strength, p.power_long_shots, p.mentality_aggression, p.mentality_interceptions, p.mentality_positioning, p.mentality_vision, p.mentality_penalties, p.mentality_composure, p.defending_marking_awareness, p.defending_standing_tackle, p.defending_sliding_tackle, p.goalkeeping_diving, p.goalkeeping_handling, p.goalkeeping_kicking, p.goalkeeping_positioning, p.goalkeeping_reflexes, p.goalkeeping_speed, p.ls, p.st, p.rs, p.lw, p.lf, p.cf, p.rf, p.rw, p.lam, p.cam, p.ram, p.lm, p.lcm, p.cm, p.rcm, p.rm, p.lwb, p.ldm, p.cdm, p.rdm, p.rwb, p.lb, p.lcb, p.cb, p.rcb, p.rb, p.gk, p.player_face_url, sp.position_slot
FROM players p
JOIN squad_player sp ON p.player_id = sp.player_id
WHERE sp.squad_id = $1
`

type GetSquadPlayersRow struct {
	PlayerID                   int32          `json:"player_id"`
	PlayerUrl                  sql.NullString `json:"player_url"`
	FifaVersion                sql.NullInt16  `json:"fifa_version"`
	FifaUpdate                 sql.NullInt16  `json:"fifa_update"`
	FifaUpdateDate             sql.NullTime   `json:"fifa_update_date"`
	ShortName                  sql.NullString `json:"short_name"`
	LongName                   sql.NullString `json:"long_name"`
	PlayerPositions            sql.NullString `json:"player_positions"`
	Overall                    sql.NullInt16  `json:"overall"`
	Potential                  sql.NullInt16  `json:"potential"`
	ValueEur                   sql.NullInt64  `json:"value_eur"`
	WageEur                    sql.NullInt32  `json:"wage_eur"`
	Age                        sql.NullInt16  `json:"age"`
	Dob                        sql.NullTime   `json:"dob"`
	HeightCm                   sql.NullInt16  `json:"height_cm"`
	WeightKg                   sql.NullInt16  `json:"weight_kg"`
	LeagueID                   sql.NullInt32  `json:"league_id"`
	LeagueName                 sql.NullString `json:"league_name"`
	LeagueLevel                sql.NullInt16  `json:"league_level"`
	ClubTeamID                 sql.NullInt32  `json:"club_team_id"`
	ClubName                   sql.NullString `json:"club_name"`
	ClubPosition               sql.NullString `json:"club_position"`
	ClubJerseyNumber           sql.NullInt16  `json:"club_jersey_number"`
	ClubLoanedFrom             sql.NullString `json:"club_loaned_from"`
	ClubJoinedDate             sql.NullTime   `json:"club_joined_date"`
	ClubContractValidUntilYear sql.NullInt16  `json:"club_contract_valid_until_year"`
	NationalityID              sql.NullInt32  `json:"nationality_id"`
	NationalityName            sql.NullString `json:"nationality_name"`
	NationTeamID               sql.NullInt32  `json:"nation_team_id"`
	NationPosition             sql.NullString `json:"nation_position"`
	NationJerseyNumber         sql.NullInt16  `json:"nation_jersey_number"`
	PreferredFoot              sql.NullString `json:"preferred_foot"`
	WeakFoot                   sql.NullInt16  `json:"weak_foot"`
	SkillMoves                 sql.NullInt16  `json:"skill_moves"`
	InternationalReputation    sql.NullInt16  `json:"international_reputation"`
	WorkRate                   sql.NullString `json:"work_rate"`
	BodyType                   sql.NullString `json:"body_type"`
	RealFace                   sql.NullBool   `json:"real_face"`
	ReleaseClauseEur           sql.NullInt64  `json:"release_clause_eur"`
	PlayerTags                 sql.NullString `json:"player_tags"`
	PlayerTraits               sql.NullString `json:"player_traits"`
	Pace                       sql.NullInt16  `json:"pace"`
	Shooting                   sql.NullInt16  `json:"shooting"`
	Passing                    sql.NullInt16  `json:"passing"`
	Dribbling                  sql.NullInt16  `json:"dribbling"`
	Defending                  sql.NullInt16  `json:"defending"`
	Physic                     sql.NullInt16  `json:"physic"`
	AttackingCrossing          sql.NullInt16  `json:"attacking_crossing"`
	AttackingFinishing         sql.NullInt16  `json:"attacking_finishing"`
	AttackingHeadingAccuracy   sql.NullInt16  `json:"attacking_heading_accuracy"`
	AttackingShortPassing      sql.NullInt16  `json:"attacking_short_passing"`
	AttackingVolleys           sql.NullInt16  `json:"attacking_volleys"`
	SkillDribbling             sql.NullInt16  `json:"skill_dribbling"`
	SkillCurve                 sql.NullInt16  `json:"skill_curve"`
	SkillFkAccuracy            sql.NullInt16  `json:"skill_fk_accuracy"`
	SkillLongPassing           sql.NullInt16  `json:"skill_long_passing"`
	SkillBallControl           sql.NullInt16  `json:"skill_ball_control"`
	MovementAcceleration       sql.NullInt16  `json:"movement_acceleration"`
	MovementSprintSpeed        sql.NullInt16  `json:"movement_sprint_speed"`
	MovementAgility            sql.NullInt16  `json:"movement_agility"`
	MovementReactions          sql.NullInt16  `json:"movement_reactions"`
	MovementBalance            sql.NullInt16  `json:"movement_balance"`
	PowerShotPower             sql.NullInt16  `json:"power_shot_power"`
	PowerJumping               sql.NullInt16  `json:"power_jumping"`
	PowerStamina               sql.NullInt16  `json:"power_stamina"`
	PowerStrength              sql.NullInt16  `json:"power_strength"`
	PowerLongShots             sql.NullInt16  `json:"power_long_shots"`
	MentalityAggression        sql.NullInt16  `json:"mentality_aggression"`
	MentalityInterceptions     sql.NullInt16  `json:"mentality_interceptions"`
	MentalityPositioning       sql.NullInt16  `json:"mentality_positioning"`
	MentalityVision            sql.NullInt16  `json:"mentality_vision"`
	MentalityPenalties         sql.NullInt16  `json:"mentality_penalties"`
	MentalityComposure         sql.NullInt16  `json:"mentality_composure"`
	DefendingMarkingAwareness  sql.NullInt16  `json:"defending_marking_awareness"`
	DefendingStandingTackle    sql.NullInt16  `json:"defending_standing_tackle"`
	DefendingSlidingTackle     sql.NullInt16  `json:"defending_sliding_tackle"`
	GoalkeepingDiving          sql.NullInt16  `json:"goalkeeping_diving"`
	GoalkeepingHandling        sql.NullInt16  `json:"goalkeeping_handling"`
	GoalkeepingKicking         sql.NullInt16  `json:"goalkeeping_kicking"`
	GoalkeepingPositioning     sql.NullInt16  `json:"goalkeeping_positioning"`
	GoalkeepingReflexes        sql.NullInt16  `json:"goalkeeping_reflexes"`
	GoalkeepingSpeed           sql.NullInt16  `json:"goalkeeping_speed"`
	Ls                         sql.NullString `json:"ls"`
	St                         sql.NullString `json:"st"`
	Rs                         sql.NullString `json:"rs"`
	Lw                         sql.NullString `json:"lw"`
	Lf                         sql.NullString `json:"lf"`
	Cf                         sql.NullString `json:"cf"`
	Rf                         sql.NullString `json:"rf"`
	Rw                         sql.NullString `json:"rw"`
	Lam                        sql.NullString `json:"lam"`
	Cam                        sql.NullString `json:"cam"`
	Ram                        sql.NullString `json:"ram"`
	Lm                         sql.NullString `json:"lm"`
	Lcm                        sql.NullString `json:"lcm"`
	Cm                         sql.NullString `json:"cm"`
	Rcm                        sql.NullString `json:"rcm"`
	Rm                         sql.NullString `json:"rm"`
	Lwb                        sql.NullString `json:"lwb"`
	Ldm                        sql.NullString `json:"ldm"`
	Cdm                        sql.NullString `json:"cdm"`
	Rdm                        sql.NullString `json:"rdm"`
	Rwb                        sql.NullString `json:"rwb"`
	Lb                         sql.NullString `json:"lb"`
	Lcb                        sql.NullString `json:"lcb"`
	Cb                         sql.NullString `json:"cb"`
	Rcb                        sql.NullString `json:"rcb"`
	Rb                         sql.NullString `json:"rb"`
	Gk                         sql.NullString `json:"gk"`
	PlayerFaceUrl              sql.NullString `json:"player_face_url"`
	PositionSlot               sql.NullString `json:"position_slot"`
}

func (q *Queries) GetSquadPlayers(ctx context.Context, squadID int32) ([]GetSquadPlayersRow, error) {
	rows, err := q.query(ctx, q.getSquadPlayersStmt, getSquadPlayers, squadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSquadPlayersRow
	for rows.Next() {
		var i GetSquadPlayersRow
		if err := rows.Scan(
			&i.PlayerID,
			&i.PlayerUrl,
			&i.FifaVersion,
			&i.FifaUpdate,
			&i.FifaUpdateDate,
			&i.ShortName,
			&i.LongName,
			&i.PlayerPositions,
			&i.Overall,
			&i.Potential,
			&i.ValueEur,
			&i.WageEur,
			&i.Age,
			&i.Dob,
			&i.HeightCm,
			&i.WeightKg,
			&i.LeagueID,
			&i.LeagueName,
			&i.LeagueLevel,
			&i.ClubTeamID,
			&i.ClubName,
			&i.ClubPosition,
			&i.ClubJerseyNumber,
			&i.ClubLoanedFrom,
			&i.ClubJoinedDate,
			&i.ClubContractValidUntilYear,
			&i.NationalityID,
			&i.NationalityName,
			&i.NationTeamID,
			&i.NationPosition,
			&i.NationJerseyNumber,
			&i.PreferredFoot,
			&i.WeakFoot,
			&i.SkillMoves,
			&i.InternationalReputation,
			&i.WorkRate,
			&i.BodyType,
			&i.RealFace,
			&i.ReleaseClauseEur,
			&i.PlayerTags,
			&i.PlayerTraits,
			&i.Pace,
			&i.Shooting,
			&i.Passing,
			&i.Dribbling,
			&i.Defending,
			&i.Physic,
			&i.AttackingCrossing,
			&i.AttackingFinishing,
			&i.AttackingHeadingAccuracy,
			&i.AttackingShortPassing,
			&i.AttackingVolleys,
			&i.SkillDribbling,
			&i.SkillCurve,
			&i.SkillFkAccuracy,
			&i.SkillLongPassing,
			&i.SkillBallControl,
			&i.MovementAcceleration,
			&i.MovementSprintSpeed,
			&i.MovementAgility,
			&i.MovementReactions,
			&i.MovementBalance,
			&i.PowerShotPower,
			&i.PowerJumping,
			&i.PowerStamina,
			&i.PowerStrength,
			&i.PowerLongShots,
			&i.MentalityAggression,
			&i.MentalityInterceptions,
			&i.MentalityPositioning,
			&i.MentalityVision,
			&i.MentalityPenalties,
			&i.MentalityComposure,
			&i.DefendingMarkingAwareness,
			&i.DefendingStandingTackle,
			&i.DefendingSlidingTackle,
			&i.GoalkeepingDiving,
			&i.GoalkeepingHandling,
			&i.GoalkeepingKicking,
			&i.GoalkeepingPositioning,
			&i.GoalkeepingReflexes,
			&i.GoalkeepingSpeed,
			&i.Ls,
			&i.St,
			&i.Rs,
			&i.Lw,
			&i.Lf,
			&i.Cf,
			&i.Rf,
			&i.Rw,
			&i.Lam,
			&i.Cam,
			&i.Ram,
			&i.Lm,
			&i.Lcm,
			&i.Cm,
			&i.Rcm,
			&i.Rm,
			&i.Lwb,
			&i.Ldm,
			&i.Cdm,
			&i.Rdm,
			&i.Rwb,
			&i.Lb,
			&i.Lcb,
			&i.Cb,
			&i.Rcb,
			&i.Rb,
			&i.Gk,
			&i.PlayerFaceUrl,
			&i.PositionSlot,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT user_id, username, email, password_hash FROM users
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.queryRow(ctx, q.getUserByEmailStmt, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT user_id, username, email, password_hash FROM users
WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, userID int32) (User, error) {
	row := q.queryRow(ctx, q.getUserByIDStmt, getUserByID, userID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT user_id, username, email, password_hash FROM users
WHERE username = $1 LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.queryRow(ctx, q.getUserByUsernameStmt, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
	)
	return i, err
}

const listPlayers = `-- name: ListPlayers :many
SELECT player_id, player_url, fifa_version, fifa_update, fifa_update_date, short_name, long_name, player_positions, overall, potential, value_eur, wage_eur, age, dob, height_cm, weight_kg, league_id, league_name, league_level, club_team_id, club_name, club_position, club_jersey_number, club_loaned_from, club_joined_date, club_contract_valid_until_year, nationality_id, nationality_name, nation_team_id, nation_position, nation_jersey_number, preferred_foot, weak_foot, skill_moves, international_reputation, work_rate, body_type, real_face, release_clause_eur, player_tags, player_traits, pace, shooting, passing, dribbling, defending, physic, attacking_crossing, attacking_finishing, attacking_heading_accuracy, attacking_short_passing, attacking_volleys, skill_dribbling, skill_curve, skill_fk_accuracy, skill_long_passing, skill_ball_control, movement_acceleration, movement_sprint_speed, movement_agility, movement_reactions, movement_balance, power_shot_power, power_jumping, power_stamina, power_strength, power_long_shots, mentality_aggression, mentality_interceptions, mentality_positioning, mentality_vision, mentality_penalties, mentality_composure, defending_marking_awareness, defending_standing_tackle, defending_sliding_tackle, goalkeeping_diving, goalkeeping_handling, goalkeeping_kicking, goalkeeping_positioning, goalkeeping_reflexes, goalkeeping_speed, ls, st, rs, lw, lf, cf, rf, rw, lam, cam, ram, lm, lcm, cm, rcm, rm, lwb, ldm, cdm, rdm, rwb, lb, lcb, cb, rcb, rb, gk, player_face_url FROM players
ORDER BY overall DESC
LIMIT $1 OFFSET $2
`

type ListPlayersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListPlayers(ctx context.Context, arg ListPlayersParams) ([]Player, error) {
	rows, err := q.query(ctx, q.listPlayersStmt, listPlayers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Player
	for rows.Next() {
		var i Player
		if err := rows.Scan(
			&i.PlayerID,
			&i.PlayerUrl,
			&i.FifaVersion,
			&i.FifaUpdate,
			&i.FifaUpdateDate,
			&i.ShortName,
			&i.LongName,
			&i.PlayerPositions,
			&i.Overall,
			&i.Potential,
			&i.ValueEur,
			&i.WageEur,
			&i.Age,
			&i.Dob,
			&i.HeightCm,
			&i.WeightKg,
			&i.LeagueID,
			&i.LeagueName,
			&i.LeagueLevel,
			&i.ClubTeamID,
			&i.ClubName,
			&i.ClubPosition,
			&i.ClubJerseyNumber,
			&i.ClubLoanedFrom,
			&i.ClubJoinedDate,
			&i.ClubContractValidUntilYear,
			&i.NationalityID,
			&i.NationalityName,
			&i.NationTeamID,
			&i.NationPosition,
			&i.NationJerseyNumber,
			&i.PreferredFoot,
			&i.WeakFoot,
			&i.SkillMoves,
			&i.InternationalReputation,
			&i.WorkRate,
			&i.BodyType,
			&i.RealFace,
			&i.ReleaseClauseEur,
			&i.PlayerTags,
			&i.PlayerTraits,
			&i.Pace,
			&i.Shooting,
			&i.Passing,
			&i.Dribbling,
			&i.Defending,
			&i.Physic,
			&i.AttackingCrossing,
			&i.AttackingFinishing,
			&i.AttackingHeadingAccuracy,
			&i.AttackingShortPassing,
			&i.AttackingVolleys,
			&i.SkillDribbling,
			&i.SkillCurve,
			&i.SkillFkAccuracy,
			&i.SkillLongPassing,
			&i.SkillBallControl,
			&i.MovementAcceleration,
			&i.MovementSprintSpeed,
			&i.MovementAgility,
			&i.MovementReactions,
			&i.MovementBalance,
			&i.PowerShotPower,
			&i.PowerJumping,
			&i.PowerStamina,
			&i.PowerStrength,
			&i.PowerLongShots,
			&i.MentalityAggression,
			&i.MentalityInterceptions,
			&i.MentalityPositioning,
			&i.MentalityVision,
			&i.MentalityPenalties,
			&i.MentalityComposure,
			&i.DefendingMarkingAwareness,
			&i.DefendingStandingTackle,
			&i.DefendingSlidingTackle,
			&i.GoalkeepingDiving,
			&i.GoalkeepingHandling,
			&i.GoalkeepingKicking,
			&i.GoalkeepingPositioning,
			&i.GoalkeepingReflexes,
			&i.GoalkeepingSpeed,
			&i.Ls,
			&i.St,
			&i.Rs,
			&i.Lw,
			&i.Lf,
			&i.Cf,
			&i.Rf,
			&i.Rw,
			&i.Lam,
			&i.Cam,
			&i.Ram,
			&i.Lm,
			&i.Lcm,
			&i.Cm,
			&i.Rcm,
			&i.Rm,
			&i.Lwb,
			&i.Ldm,
			&i.Cdm,
			&i.Rdm,
			&i.Rwb,
			&i.Lb,
			&i.Lcb,
			&i.Cb,
			&i.Rcb,
			&i.Rb,
			&i.Gk,
			&i.PlayerFaceUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removePlayerFromSquad = `-- name: RemovePlayerFromSquad :exec
DELETE FROM squad_player
WHERE squad_id = $1 AND player_id = $2
`

type RemovePlayerFromSquadParams struct {
	SquadID  int32 `json:"squad_id"`
	PlayerID int32 `json:"player_id"`
}

func (q *Queries) RemovePlayerFromSquad(ctx context.Context, arg RemovePlayerFromSquadParams) error {
	_, err := q.exec(ctx, q.removePlayerFromSquadStmt, removePlayerFromSquad, arg.SquadID, arg.PlayerID)
	return err
}

const searchPlayers = `-- name: SearchPlayers :many
SELECT player_id, player_url, fifa_version, fifa_update, fifa_update_date, short_name, long_name, player_positions, overall, potential, value_eur, wage_eur, age, dob, height_cm, weight_kg, league_id, league_name, league_level, club_team_id, club_name, club_position, club_jersey_number, club_loaned_from, club_joined_date, club_contract_valid_until_year, nationality_id, nationality_name, nation_team_id, nation_position, nation_jersey_number, preferred_foot, weak_foot, skill_moves, international_reputation, work_rate, body_type, real_face, release_clause_eur, player_tags, player_traits, pace, shooting, passing, dribbling, defending, physic, attacking_crossing, attacking_finishing, attacking_heading_accuracy, attacking_short_passing, attacking_volleys, skill_dribbling, skill_curve, skill_fk_accuracy, skill_long_passing, skill_ball_control, movement_acceleration, movement_sprint_speed, movement_agility, movement_reactions, movement_balance, power_shot_power, power_jumping, power_stamina, power_strength, power_long_shots, mentality_aggression, mentality_interceptions, mentality_positioning, mentality_vision, mentality_penalties, mentality_composure, defending_marking_awareness, defending_standing_tackle, defending_sliding_tackle, goalkeeping_diving, goalkeeping_handling, goalkeeping_kicking, goalkeeping_positioning, goalkeeping_reflexes, goalkeeping_speed, ls, st, rs, lw, lf, cf, rf, rw, lam, cam, ram, lm, lcm, cm, rcm, rm, lwb, ldm, cdm, rdm, rwb, lb, lcb, cb, rcb, rb, gk, player_face_url FROM players
WHERE short_name ILIKE $1 OR long_name ILIKE $1
ORDER BY overall DESC
LIMIT $2 OFFSET $3
`

type SearchPlayersParams struct {
	ShortName sql.NullString `json:"short_name"`
	Limit     int32          `json:"limit"`
	Offset    int32          `json:"offset"`
}

func (q *Queries) SearchPlayers(ctx context.Context, arg SearchPlayersParams) ([]Player, error) {
	rows, err := q.query(ctx, q.searchPlayersStmt, searchPlayers, arg.ShortName, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Player
	for rows.Next() {
		var i Player
		if err := rows.Scan(
			&i.PlayerID,
			&i.PlayerUrl,
			&i.FifaVersion,
			&i.FifaUpdate,
			&i.FifaUpdateDate,
			&i.ShortName,
			&i.LongName,
			&i.PlayerPositions,
			&i.Overall,
			&i.Potential,
			&i.ValueEur,
			&i.WageEur,
			&i.Age,
			&i.Dob,
			&i.HeightCm,
			&i.WeightKg,
			&i.LeagueID,
			&i.LeagueName,
			&i.LeagueLevel,
			&i.ClubTeamID,
			&i.ClubName,
			&i.ClubPosition,
			&i.ClubJerseyNumber,
			&i.ClubLoanedFrom,
			&i.ClubJoinedDate,
			&i.ClubContractValidUntilYear,
			&i.NationalityID,
			&i.NationalityName,
			&i.NationTeamID,
			&i.NationPosition,
			&i.NationJerseyNumber,
			&i.PreferredFoot,
			&i.WeakFoot,
			&i.SkillMoves,
			&i.InternationalReputation,
			&i.WorkRate,
			&i.BodyType,
			&i.RealFace,
			&i.ReleaseClauseEur,
			&i.PlayerTags,
			&i.PlayerTraits,
			&i.Pace,
			&i.Shooting,
			&i.Passing,
			&i.Dribbling,
			&i.Defending,
			&i.Physic,
			&i.AttackingCrossing,
			&i.AttackingFinishing,
			&i.AttackingHeadingAccuracy,
			&i.AttackingShortPassing,
			&i.AttackingVolleys,
			&i.SkillDribbling,
			&i.SkillCurve,
			&i.SkillFkAccuracy,
			&i.SkillLongPassing,
			&i.SkillBallControl,
			&i.MovementAcceleration,
			&i.MovementSprintSpeed,
			&i.MovementAgility,
			&i.MovementReactions,
			&i.MovementBalance,
			&i.PowerShotPower,
			&i.PowerJumping,
			&i.PowerStamina,
			&i.PowerStrength,
			&i.PowerLongShots,
			&i.MentalityAggression,
			&i.MentalityInterceptions,
			&i.MentalityPositioning,
			&i.MentalityVision,
			&i.MentalityPenalties,
			&i.MentalityComposure,
			&i.DefendingMarkingAwareness,
			&i.DefendingStandingTackle,
			&i.DefendingSlidingTackle,
			&i.GoalkeepingDiving,
			&i.GoalkeepingHandling,
			&i.GoalkeepingKicking,
			&i.GoalkeepingPositioning,
			&i.GoalkeepingReflexes,
			&i.GoalkeepingSpeed,
			&i.Ls,
			&i.St,
			&i.Rs,
			&i.Lw,
			&i.Lf,
			&i.Cf,
			&i.Rf,
			&i.Rw,
			&i.Lam,
			&i.Cam,
			&i.Ram,
			&i.Lm,
			&i.Lcm,
			&i.Cm,
			&i.Rcm,
			&i.Rm,
			&i.Lwb,
			&i.Ldm,
			&i.Cdm,
			&i.Rdm,
			&i.Rwb,
			&i.Lb,
			&i.Lcb,
			&i.Cb,
			&i.Rcb,
			&i.Rb,
			&i.Gk,
			&i.PlayerFaceUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePointsForNation = `-- name: UpdatePointsForNation :exec
UPDATE squad s
SET total_points = total_points + ($1 * (
    SELECT COUNT(*) FROM squad_player sp
    JOIN players p ON sp.player_id = p.player_id
    WHERE sp.squad_id = s.squad_id AND p.nationality_id = $2
))
WHERE EXISTS (
    SELECT 1 FROM squad_player sp
    JOIN players p ON sp.player_id = p.player_id
    WHERE sp.squad_id = s.squad_id AND p.nationality_id = $2
)
`

type UpdatePointsForNationParams struct {
	PlayerID      int32         `json:"player_id"`
	NationalityID sql.NullInt32 `json:"nationality_id"`
}

func (q *Queries) UpdatePointsForNation(ctx context.Context, arg UpdatePointsForNationParams) error {
	_, err := q.exec(ctx, q.updatePointsForNationStmt, updatePointsForNation, arg.PlayerID, arg.NationalityID)
	return err
}

const updateSquadBudget = `-- name: UpdateSquadBudget :one
UPDATE squad
SET budget_used = $2
WHERE squad_id = $1
RETURNING squad_id, user_id, squad_name, formation, budget_used, total_points
`

type UpdateSquadBudgetParams struct {
	SquadID    int32         `json:"squad_id"`
	BudgetUsed sql.NullInt64 `json:"budget_used"`
}

func (q *Queries) UpdateSquadBudget(ctx context.Context, arg UpdateSquadBudgetParams) (Squad, error) {
	row := q.queryRow(ctx, q.updateSquadBudgetStmt, updateSquadBudget, arg.SquadID, arg.BudgetUsed)
	var i Squad
	err := row.Scan(
		&i.SquadID,
		&i.UserID,
		&i.SquadName,
		&i.Formation,
		&i.BudgetUsed,
		&i.TotalPoints,
	)
	return i, err
}

const updateSquadFormation = `-- name: UpdateSquadFormation :one
UPDATE squad
SET formation = $2
WHERE squad_id = $1
RETURNING squad_id, user_id, squad_name, formation, budget_used, total_points
`

type UpdateSquadFormationParams struct {
	SquadID   int32          `json:"squad_id"`
	Formation sql.NullString `json:"formation"`
}

func (q *Queries) UpdateSquadFormation(ctx context.Context, arg UpdateSquadFormationParams) (Squad, error) {
	row := q.queryRow(ctx, q.updateSquadFormationStmt, updateSquadFormation, arg.SquadID, arg.Formation)
	var i Squad
	err := row.Scan(
		&i.SquadID,
		&i.UserID,
		&i.SquadName,
		&i.Formation,
		&i.BudgetUsed,
		&i.TotalPoints,
	)
	return i, err
}
