export interface CountryOption {
  id: number;
  name: string;
}

export const COUNTRY_OPTIONS: CountryOption[] = [
  { id: 149, name: 'Afghanistan' },
  { id: 1, name: 'Albania' },
  { id: 97, name: 'Algeria' },
  { id: 2, name: 'Andorra' },
  { id: 98, name: 'Angola' },
  { id: 63, name: 'Antigua and Barbuda' },
  { id: 52, name: 'Argentina' },
  { id: 3, name: 'Armenia' },
  { id: 195, name: 'Australia' },
  { id: 4, name: 'Austria' },
  { id: 5, name: 'Azerbaijan' },
  { id: 151, name: 'Bangladesh' },
  { id: 66, name: 'Barbados' },
  { id: 6, name: 'Belarus' },
  { id: 7, name: 'Belgium' },
  { id: 99, name: 'Benin' },
  { id: 68, name: 'Bermuda' },
  { id: 53, name: 'Bolivia' },
  { id: 8, name: 'Bosnia and Herzegovina' },
  { id: 54, name: 'Brazil' },
  { id: 9, name: 'Bulgaria' },
  { id: 101, name: 'Burkina Faso' },
  { id: 102, name: 'Burundi' },
  { id: 104, name: 'Cabo Verde' },
  { id: 103, name: 'Cameroon' },
  { id: 70, name: 'Canada' },
  { id: 105, name: 'Central African Republic' },
  { id: 106, name: 'Chad' },
  { id: 55, name: 'Chile' },
  { id: 155, name: 'China PR' },
  { id: 213, name: 'Chinese Taipei' },
  { id: 56, name: 'Colombia' },
  { id: 214, name: 'Comoros' },
  { id: 107, name: 'Congo' },
  { id: 110, name: 'Congo DR' },
  { id: 72, name: 'Costa Rica' },
  { id: 10, name: 'Croatia' },
  { id: 73, name: 'Cuba' },
  { id: 85, name: 'Curacao' },
  { id: 11, name: 'Cyprus' },
  { id: 12, name: 'Czechia' },
  { id: 108, name: "Côte d'Ivoire" },
  { id: 13, name: 'Denmark' },
  { id: 207, name: 'Dominican Republic' },
  { id: 57, name: 'Ecuador' },
  { id: 111, name: 'Egypt' },
  { id: 76, name: 'El Salvador' },
  { id: 14, name: 'England' },
  { id: 112, name: 'Equatorial Guinea' },
  { id: 208, name: 'Estonia' },
  { id: 16, name: 'Faroe Islands' },
  { id: 17, name: 'Finland' },
  { id: 18, name: 'France' },
  { id: 115, name: 'Gabon' },
  { id: 116, name: 'Gambia' },
  { id: 20, name: 'Georgia' },
  { id: 21, name: 'Germany' },
  { id: 117, name: 'Ghana' },
  { id: 205, name: 'Gibraltar' },
  { id: 22, name: 'Greece' },
  { id: 77, name: 'Grenada' },
  { id: 78, name: 'Guatemala' },
  { id: 118, name: 'Guinea' },
  { id: 119, name: 'Guinea-Bissau' },
  { id: 79, name: 'Guyana' },
  { id: 80, name: 'Haiti' },
  { id: 81, name: 'Honduras' },
  { id: 158, name: 'Hong Kong' },
  { id: 23, name: 'Hungary' },
  { id: 24, name: 'Iceland' },
  { id: 159, name: 'India' },
  { id: 160, name: 'Indonesia' },
  { id: 161, name: 'Iran' },
  { id: 162, name: 'Iraq' },
  { id: 26, name: 'Israel' },
  { id: 27, name: 'Italy' },
  { id: 82, name: 'Jamaica' },
  { id: 163, name: 'Japan' },
  { id: 164, name: 'Jordan' },
  { id: 120, name: 'Kenya' },
  { id: 167, name: 'Korea Republic' },
  { id: 219, name: 'Kosovo' },
  { id: 28, name: 'Latvia' },
  { id: 171, name: 'Lebanon' },
  { id: 122, name: 'Liberia' },
  { id: 123, name: 'Libya' },
  { id: 29, name: 'Liechtenstein' },
  { id: 30, name: 'Lithuania' },
  { id: 31, name: 'Luxembourg' },
  { id: 124, name: 'Madagascar' },
  { id: 125, name: 'Malawi' },
  { id: 173, name: 'Malaysia' },
  { id: 126, name: 'Mali' },
  { id: 32, name: 'Malta' },
  { id: 127, name: 'Mauritania' },
  { id: 83, name: 'Mexico' },
  { id: 33, name: 'Moldova' },
  { id: 15, name: 'Montenegro' },
  { id: 84, name: 'Montserrat' },
  { id: 129, name: 'Morocco' },
  { id: 130, name: 'Mozambique' },
  { id: 131, name: 'Namibia' },
  { id: 34, name: 'Netherlands' },
  { id: 215, name: 'New Caledonia' },
  { id: 198, name: 'New Zealand' },
  { id: 132, name: 'Niger' },
  { id: 133, name: 'Nigeria' },
  { id: 19, name: 'North Macedonia' },
  { id: 35, name: 'Northern Ireland' },
  { id: 36, name: 'Norway' },
  { id: 179, name: 'Pakistan' },
  { id: 180, name: 'Palestine' },
  { id: 87, name: 'Panama' },
  { id: 58, name: 'Paraguay' },
  { id: 59, name: 'Peru' },
  { id: 181, name: 'Philippines' },
  { id: 37, name: 'Poland' },
  { id: 38, name: 'Portugal' },
  { id: 88, name: 'Puerto Rico' },
  { id: 182, name: 'Qatar' },
  { id: 25, name: 'Republic of Ireland' },
  { id: 39, name: 'Romania' },
  { id: 40, name: 'Russia' },
  { id: 134, name: 'Rwanda' },
  { id: 89, name: 'Saint Kitts and Nevis' },
  { id: 90, name: 'Saint Lucia' },
  { id: 183, name: 'Saudi Arabia' },
  { id: 42, name: 'Scotland' },
  { id: 136, name: 'Senegal' },
  { id: 51, name: 'Serbia' },
  { id: 138, name: 'Sierra Leone' },
  { id: 43, name: 'Slovakia' },
  { id: 44, name: 'Slovenia' },
  { id: 139, name: 'Somalia' },
  { id: 140, name: 'South Africa' },
  { id: 45, name: 'Spain' },
  { id: 185, name: 'Sri Lanka' },
  { id: 92, name: 'Suriname' },
  { id: 46, name: 'Sweden' },
  { id: 47, name: 'Switzerland' },
  { id: 186, name: 'Syria' },
  { id: 187, name: 'Tajikistan' },
  { id: 143, name: 'Tanzania' },
  { id: 188, name: 'Thailand' },
  { id: 144, name: 'Togo' },
  { id: 93, name: 'Trinidad and Tobago' },
  { id: 145, name: 'Tunisia' },
  { id: 48, name: 'Türkiye' },
  { id: 146, name: 'Uganda' },
  { id: 49, name: 'Ukraine' },
  { id: 190, name: 'United Arab Emirates' },
  { id: 95, name: 'United States' },
  { id: 60, name: 'Uruguay' },
  { id: 191, name: 'Uzbekistan' },
  { id: 204, name: 'Vanuatu' },
  { id: 61, name: 'Venezuela' },
  { id: 50, name: 'Wales' },
  { id: 193, name: 'Yemen' },
  { id: 147, name: 'Zambia' },
  { id: 148, name: 'Zimbabwe' },
];

// O(1) lookup for country name -> country id.
export const COUNTRY_ID_BY_NAME = new Map<string, number>(
  COUNTRY_OPTIONS.map(country => [country.name, country.id])
);

// O(1) lookup for country id -> country name.
export const COUNTRY_NAME_BY_ID = new Map<number, string>(
  COUNTRY_OPTIONS.map(country => [country.id, country.name])
);
